baseURL = 'https://trevarj.github.io/'
languageCode = 'en-us'
title = "Trevor Arjeski's Site"
theme = "cactus"
copyright = "Trevor Arjeski"

[params]
colortheme = "dark"
description = "I am a programmer."
mainSection = "about"
mainSectionTitle = "About"
rss = true

[[params.social]]
  name = "github"
  link = "https://github.com/trevarj"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/arjeski"

[[params.social]]
  name = "email"
  link = "tmarjeski@gmail.com" # no need for "mailto:" at the start

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
