baseURL = 'https://trevarj.github.io'
languageCode = 'en-us'
title = "Trevor Arjeski's Site"
theme = "cactus"
copyright = "Trevor Arjeski"

[params]
colortheme = "dark"
description = """
I am a programmer working with Rust in the crypto industry.

GPG Key: A6C20D0C2AD838F949070EA3A52D68794EBED758
"""
mainSection = "posts"
mainSectionTitle = "Posts"
rss = true
showProjectsList = true

[[params.social]]
  name = "github"
  link = "https://github.com/trevarj"

[[params.social]]
  name = "github"
  link = "https://github.com/trevor-crypto"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/arjeski"

[[params.social]]
  name = "email"
  link = "tmarjeski@gmail.com" # no need for "mailto:" at the start

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4
